version: 2
jobs:
  deploy:
    docker:
      - image: circleci/python:2.7-jessie

    working_directory: ~/repo
    
    steps:
      - checkout
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy engelberg.lol
          command: aws s3 sync engelberg.lol/ s3://engelberg.lol/ --delete
      - run:
          name: Deploy alex.engelberg.lol
          command: aws s3 sync alex.engelberg.lol/ s3://alex.engelberg.lol/ --delete
      - run:
          name: Deploy molly.engelberg.lol
          command: aws s3 sync molly.engelberg.lol/ s3://molly.engelberg.lol/ --delete

workflows:
  version: 2
  deploy-site:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
