version: 2
jobs:
  build-alex:
    docker:
      - image: circleci/clojure:lein-2.8.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - alex-m2-{{ checksum "alex.engelberg.lol/project.clj" }}-{{ .Revision }}
            - alex-m2-{{ checksum "alex.engelberg.lol/project.clj" }}-
            - alex-m2-
      - run:
          working_directory: alex.engelberg.lol
          name: Build JS
          command: lein cljsbuild once min
      - save_cache:
          key: alex-m2-{{ checksum "alex.engelberg.lol/project.clj" }}-{{ .Revision }}
          paths:
            - ~/.m2
      - save_cache:
          key: alex-built-js-{{ .Environment.CIRCLE_WORKFLOW_ID }}
          paths:
            - alex.engelberg.lol/resources/public/js/compiled
  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - restore_cache:
          keys:
            - alex-built-js-{{ .Environment.CIRCLE_WORKFLOW_ID }}
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy engelberg.lol
          command: aws s3 sync engelberg.lol/ s3://engelberg.lol/ --delete
      - run:
          name: Deploy alex.engelberg.lol
          command: aws s3 sync alex.engelberg.lol/resources/public/ s3://alex.engelberg.lol/ --delete
      - run:
          name: Deploy molly.engelberg.lol
          command: aws s3 sync molly.engelberg.lol/ s3://molly.engelberg.lol/ --delete

workflows:
  version: 2
  build-site:
    jobs:
      - build-alex
      - deploy:
          requires:
            - build-alex
          filters:
            branches:
              only:
                - master
